server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 0
logging:
  level: INFO
  appenders:
    - type: console
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
