server:
  applicationConnectors:
    - type: http
      port: 2447
  adminConnectors:
    - type: http
      port: 2448
logging:
  level: INFO
  appenders:
    - type: console
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
